
remote_theme: siddhantgoel/clean-jekyll-theme

title: John Doe

name: John Doe

description: Site description goes here.

baseurl: "/pendulous_rainbows"

lang: en

github_username: johndoe

social: 
    name: John Doe
    links:
        - https://twitter.com/johndoe
        - https://github.com/johndoe

